[build-system]
requires = ["setuptools >= 61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["epic_extractor"]
exclude = []
namespaces = false

[project]
name = "epic_extractor"
dynamic = ["version"]
license = { file = 'LICENSE' }
description = 'Analysis package for the EPIC atmospheric model'
requires-python = ">=3.10"
dependencies = [
    'numpy>=2.2.4',
    "netcdf4",
    "tqdm>=4.67.1",
    "scipy>=1.15.3",
]
authors = [
    { name = 'Ramanakumar Sankar', email = 'ramanakumar.shankar@gmail.com' },
]
readme = "README.md"

[tool.setuptools.dynamic]
version = { attr = "epic_extractor.version.__version__" }

[project.urls]
repository = "https://www.github.com/ramanakumars/epic_extractor"

[project.scripts]
interpolate_N2 = 'epic_extractor.tools.integrate_N2:extrapolate_Tp'

[dependency-groups]
dev = [
    "coveralls>=4.0.1",
    "myst-parser>=4.0.1",
    "nbsphinx>=0.9.7",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "sphinx>=8.1.3",
    "sphinx-book-theme>=1.1.4",
]
